### ISSUE TITLE
Issues with Debian Wheezy

### ISSUE THREAD

**Issue by icco** [google/lmctfy#8]
```
$ sudo lmctfy init "
>   cgroup_mount:{
>     mount_path:'/dev/cgroup/cpu'
>     hierarchy:CGROUP_CPU hierarchy:CGROUP_CPUACCT
>   }
>   cgroup_mount:{
>     mount_path:'/dev/cgroup/cpuset' hierarchy:CGROUP_CPUSET
>   }
>   cgroup_mount:{
>     mount_path:'/dev/cgroup/freezer' hierarchy:CGROUP_FREEZER
>   }
>   cgroup_mount:{
>     mount_path:'/dev/cgroup/memory' hierarchy:CGROUP_MEMORY
>   }"
Command exited with error message: 9: Failed to mount hierarchy with ID "memory" at "/dev/cgroup/memory"
```

```
$ lmctfy  -v
lmctfy version 0.1-0
```

```
$ uname -a
Linux byok 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 GNU/Linux
```

I'm running on Google Compute Engine. (natwelch@google.com if you wanna talk off bug about how to replicate this).

**Comment by wenchma** [comment]
mars@node1:~/community/cookbooks$ sudo mount -t cgroup -o debug cgroup /cgroup
[sudo] password for mars: 
mount: mount point /cgroup does not exist
mars@node1:~/community/cookbooks$ sudo mkdir /cgroup
mars@node1:~/community/cookbooks$ sudo mount -t cgroup -o debug cgroup /cgroup
mount: special device cgroup does not exist

looks like it has no cgroup support, how to enable cgroup for operating system ?
